env:
    browser: true
    node: true
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        ecmaVersion: 2021
    project:
        - tsconfig.json
        - tsconfig.eslint.json
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/recommended-requiring-type-checking
    - plugin:react-hooks/recommended
rules:
    react-hooks/exhaustive-deps: error
    react-hooks/rules-of-hooks: error
